#Welcome to the config file of AntiSwearPlugin.
#This plugin is developed by Lightcab.

#Set the value of bannedWords to the words that you want to be banned on the server.
#Simply add another - <word> to add another word.
bannedWords:
 -
 -
 -

#Set the value of replaceMessage to the message/word that you want to be displayed when a player tells the banned word.
replaceMessage: I just sweared!

#Set the value of warnPlayer true if you want to warn the player if s/he tells the banned word.
#Set the value of warnPlayer false if you don't want to warn the player if s/he says the banned word.
warnPlayer: false

#Set the value of warnMessage to the message that you want to be displayed when the player swears.
#Note: It is only going to be used if you have set warnPlayer to true.
warnMessage:

#Set the value of setFire true if you want to set the player on fire if s/he tells the banned word.
setFire: true

#Set the value of fireSecond to the amount of seconds you want the player to be on fire.
fireSecond: 2
